import { Metadata } from "next";
import CategorySideBar from "./profile/components/CategorySideBar";
import PostInputCard from "@/components/common/Input/PostInputCard";
import Posts from "@/components/Posts/Posts";
import ActiveUserSideBar from "@/components/ActiveUserSideBar/ActiveUserSideBar";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

const Home = () => {

  return (
    <div className="flex">
      <CategorySideBar />
      <section className="flex-1 lg:px-14 px-5">
        <div className="max-w-2xl mx-auto">
          <PostInputCard />
          <Posts />
        </div>
      </section>
      <ActiveUserSideBar />
    </div>
  );
};

export default Home;