import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

const Home = () => {
  return (
    <div>
      Home
    </div>
  );
};

export default Home;